.\" $Id: tbclock.1,v 1.7 2007-02-28 12:47:35 tamentis Exp $
.\" 
.\" Copyright (c) 2007 Bertrand Janin <tamentis@neopulsar.org>
.\" All rights reserved.
.\" 
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.TH TBCLOCK 1 "February 7, 2007" "Bertrand Janin"

.SH NAME
tbclock \- binary clock with some fun features

.SH SYNOPSIS
.B tbclock
[-abdefpvh] [-HMST color] [-m module]

.SH DESCRIPTION
.B tbclock
is a fullscreen terminal clock that displays time in a binary fashion or
another. It features a few modules and games to play with binary
displayed time. By default the lines are horizontal and shows hours,
minutes and seconds, you can switch to a different behaviour with -a,
see below.
.PP
The options are as follows:
.TP
.B -v
Display version information.
.TP
.B -f
By default, if the terminal is big enough,
.B tbclock
draws a frame around the terminal with its version in the top-right corner.
This option disable this behavior.
.TP
.B -b
By default, if the terminal is big enough,
.B tbclock
draws a little space between each blocks to ease the reading, use this
switch to disable this little space.
.TP
.B -d
Do not display the dots where the bit is NUL on the clock.
.TP
.B -a
Switch 
.B tbclock
to display binary times in a different fashion, easier for some people,
one line per 'decimal digit' and vertical.
.TP
.B -e
Switch 
.B tbclock
to display decimal helpers. One -H will display side help, -HH will display
a decimal clock under the binary clock, -HHH will display both. You can
alternatively use the 'h' key to switch between modes.
.TP
.B -m <module>
.B tbclock
features games and tools related to binary clock reading, each module will
have its own keyboard bindings, check in the next section for more
information.
.TP
.B -H, -M, -S, -T <color>
Those options changes the color of blocks. It takes a numeric option between
0 and 7, those numbers are directly copied from ncurses.h, here are their
meaning :
     0: Black         4: Blue
     1: Red           5: Magenta
     2: Green         6: Cyan
     3: Yellow        7: White
.TP
.B -p
Force
.B tbclock
to use 12 hours display instead of 24, am/pm will not be shown.

.SH MODULES
.TP
.B clock
This is the default module, it displays the current time. The 'h' key
will switch between different decimal hint modes. 'a' key will switch 
between the two different display modes 'vertical' and 'horizontal'. Any
other key will quit.
.TP
.B chrono
This module will run a timer from 0 to whatever you need. You can press
the Spacebar at any time to pause the timer, and BackSpace to reset it. Any
other key will quit. This module has an extra binary line that shows tenth
of seconds, this might makes some slow terminal flicker. 'h' key will
switch on/off different reading helps, 'a' will switch between display
modes.
.TP
.B guessbin
This game displays a binary time and ask you its decimal equivalent. To
answer you have to fill the time in this form : "HH:MM:SS". The difficulty
only changes the answer delay and the amount of points you get. This module
is not affected by -f, -b or -H.

.SH AUTHORS
.B tbclock
is maintained by Bertrand Janin <tamentis@neopulsar.org>. Please visit
.I http://tamentis.com/projects/tbclock/
for more information.

.SH THANKS
.B Franck
who got a binary watch and is at the root of the idea,
.B Olivier Regnier
for the color options idea and bug reports,
.B Andrew Pantyukhin
for the FreeBSD port,
.B #debsquad @ irc.oftc.net
for the support and testing ;)

.SH "SEE ALSO"
.BR date (1)
.br
